server:
  port: 8080

zuul:
  routes:
    auth-center:
      path: /login/**
      url: http://127.0.0.1:8081/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    backend-service:
      path: /api/**
      url: http://127.0.0.1:8082/

mf.security.jwt.secret: hellotest
