server:
  port: 8081
mf.security.jwt.secret: hellotest
spring:
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/app?useUnicode=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  #redis
  redis:
    host: 192.168.32.128
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000


